version: '3'
services:
  frontend:
    image: paladln/time-app-frontend-dev
    restart: always
    ports:
      - '3000:3000'
  api:
    image: paladln/time-app-backend-dev
    restart: always
    depends_on:
      - mysql
    ports:
      - '5555:5000'
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data_pub:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  mysql_data_pub:

